version: 2

executors:
  docker_jdk:
    docker:
      - image: adoptopenjdk:11-jdk-hotspot
  vm_ubuntu:
    machine:
      image: vm_ubuntu-1604:201903-01 

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:  # required since `release_artifacts` has tag filters AND requires `build`
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release_artifacts:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - perf_test:
          requires:
            - build

jobs:
  build:
    executor: docker_jdk
    steps:
      - checkout
      - run:
          name: Set correct permissions for our .m2 cache folder
          command: sudo chmod -R 777 /root
      - run:
          name: Install Java 11
          command: |
            curl -s "https://get.sdkman.io" | bash
            echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' >> ~/.bashrc
            source ~/.bashrc
            sdk install java 11.0.2-open
            sdk default java 11.0.2-open
      - restore_cache:
          keys:
            - maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-v1-{{ .Branch }}
            - maven-v1-
      - run:
          name: Running maven
          command: |
            source ~/.bashrc
            ./mvnw --version
            ./mvnw install
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          paths:
          - ~/.m2
      - run:
          name: Collecting mirror-node assets
          command: |
            mkdir -p /tmp/workspace/mirror-node/
            mv target/mirror-node.jar /tmp/workspace/mirror-node/
            mv target/config /tmp/workspace/mirror-node/
            mv target/lib /tmp/workspace/mirror-node/
            mv systemd /tmp/workspace/mirror-node/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - mirror-node

  release_artifacts:
    executor: docker_jdk
    steps:
      - *attach_workspace
      - run:
          name: Generating mirror-node.tgz
          working_directory: /tmp/workspace/
          command: |
            _tagged_dir=mirror-node-${CIRCLE_TAG}
            mv mirror-node "${_tagged_dir}"
            tar -czf /tmp/mirror-node.tgz "${_tagged_dir}"
      - store_artifacts:
          path: /tmp/mirror-node.tgz

  perf_test:
    executor: vm_ubuntu
    steps:
      - *attach_workspace
      - add_ssh_keys:
          fingerprints:
            - "0f:b0:7b:39:f1:10:2e:87:86:8a:75:3f:0a:5a:6b:51"
      - run:
          name: Deploy over SSH to Performance Test Server
          command: |
            ssh $SSH_USER@$SSH_HOST "ls -la"