version: 2
executorType: machine

workflows:
  version: 2
  main:
    jobs:
    - build

defaults: &defaults
  docker:
  - image: adoptopenjdk:11-jdk-hotspot

jobs:
  build:
    <<: *defaults
    steps:

    - checkout
      
    - run:
        name: Install
        command: mvn -B clean install

    - store_test_results:
        path: target/surefire-reports