version: 2

workflows:
  version: 2
  main:
    jobs:
    - build

defaults: &defaults
  docker:
  - image: adoptopenjdk:11-jdk-hotspot

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
          - maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          - maven-v1-{{ .Branch }}
          - maven-v1-
    - run: ./mvnw install
    - store_test_results:
        path: target/surefire-reports
    - save_cache:
        key: maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

