version: '3.3'
services:
  # this is the database container
  mirror-node-postgres:
    build:
      context: ./
      dockerfile: Postgres
    stop_signal: SIGTERM 
    tty: true
    env_file:
      - .env
    volumes:
      - ./MirrorNodePostgresData:/var/lib/postgresql/data
      - ./runtime:/MirrorNodeCode
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: ./MirrorNodeCode/wait-for-postgres.sh

  # this downloads balance files, its behaviour is controlled by ./config/config.json
  mirror-node-balance-downloader:
    build:
      context: ./
      dockerfile: MirrorNodeImage
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: java -Dlog4j.configurationFile=./config/log4j2.xml -cp mirrorNode.jar com.hedera.downloader.AccountBalancesDownloader

  # this processes balance files and puts the result in the database, its behaviour is controlled by ./config/config.json
  mirror-node-balance-parser:
    build:
      context: ./
      dockerfile: MirrorNodeImage
    depends_on:
      - mirror-node-postgres
    environment:
      - HEDERA_MIRROR_DB_URL=jdbc:postgresql://mirror-node-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - HEDERA_MIRROR_DB_USER=${POSTGRES_USER}
      - HEDERA_MIRROR_DB_PASS=${POSTGRES_PASSWORD}
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: >
      bash -c "java -Dlog4j.configurationFile=./config/log4j2.xml -cp mirrorNode.jar com.hedera.balanceFileLogger.BalanceFileLogger
      && java -Dlog4j.configurationFile=./config/log4j2.xml -cp mirrorNode.jar com.hedera.balanceFileLogger.BalanceFileHistoryLogger"

  # this downloads record files, its behaviour is controlled by ./config/config.json
  mirror-node-record-downloader:
    build:
      context: ./
      dockerfile: MirrorNodeImage
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: java -Dlog4j.configurationFile=./config/log4j2.xml -cp mirrorNode.jar com.hedera.downloader.RecordFileDownloader

  # this processes record files and puts the result in the database, its behaviour is controlled by ./config/config.json
  mirror-node-record-parser:
    build:
      context: ./
      dockerfile: MirrorNodeImage
    depends_on:
      - mirror-node-postgres
    environment:
      - HEDERA_MIRROR_DB_URL=jdbc:postgresql://mirror-node-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - HEDERA_MIRROR_DB_USER=${POSTGRES_USER}
      - HEDERA_MIRROR_DB_PASS=${POSTGRES_PASSWORD}
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: java -Dlog4j.configurationFile=./config/log4j2.xml -cp mirrorNode.jar com.hedera.recordFileParser.RecordFileParser
