version: '3.3'
services:
  # this is the database container
  mirror-node-postgres:
    build:
      context: ./
      dockerfile: Postgres
    stop_signal: SIGTERM
    tty: true
    env_file:
      - .env
    volumes:
      - ./MirrorNodePostgresData:/var/lib/postgresql/data
      - ./runtime:/MirrorNodeCode
    ports:
      - 5433:5432

  # this downloads balance files, its behaviour is controlled by ./config/config.json
  mirror-node-balance-downloader:
    build:
      context: ./
      dockerfile: MirrorNodeClientImage
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: java -Dlog4j.configurationFile=./config/log4j2.xml -cp mirrorNode.jar com.hedera.downloader.AccountBalancesDownloader

  # this processes balance files and puts the result in the database, its behaviour is controlled by ./config/config.json
  mirror-node-balance-parser:
    build:
      context: ./
      dockerfile: MirrorNodeClientImage
    depends_on:
      - mirror-node-postgres
    environment:
      - HEDERA_MIRROR_DB_URL=jdbc:postgresql://mirror-node-postgres:5432/${POSTGRES_DB}
      - HEDERA_MIRROR_DB_USER=${POSTGRES_USER}
      - HEDERA_MIRROR_DB_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=mirror-node-postgres
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: ./balanceParse.sh

  # this downloads and processes record files and puts the result in the database, its behaviour is controlled by ./config/config.json
  mirror-node-record-download-parse:
    build:
      context: ./
      dockerfile: MirrorNodeClientImage
    depends_on:
      - mirror-node-postgres
    environment:
      - HEDERA_MIRROR_DB_URL=jdbc:postgresql://mirror-node-postgres:5432/${POSTGRES_DB}
      - HEDERA_MIRROR_DB_USER=${POSTGRES_USER}
      - HEDERA_MIRROR_DB_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=mirror-node-postgres
    working_dir: /MirrorNodeCode
    env_file:
      - .env
    volumes:
      - ./MirrorNodeData:/MirrorNodeData
      - ./runtime:/MirrorNodeCode
    command: ./recordDownloadParse.sh
